### ISSUE TITLE
kali linux ruby curb install error

### ISSUE THREAD

**Issue by okeycik** [Hood3dRob1n/creep3r#3]
./debian_setup.sh

Installing Ruby gems now....
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Your Gemfile lists the gem text-table (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Using robotex 1.0.0
Using anemone 0.7.2
Using io-like 0.3.0
Using archive-zip 0.7.0
Using bcrypt 3.1.7

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb 
```

checking for curl-config... no
checking for main() in -lcurl... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby1.9.1
    --with-curl-dir
    --without-curl-dir
    --with-curl-include
    --without-curl-include=${curl-dir}/include
    --with-curl-lib
    --without-curl-lib=${curl-dir}/lib
    --with-curllib
    --without-curllib
extconf.rb:23:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

Gem files will remain installed in /var/lib/gems/1.9.1/gems/curb-0.8.6 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/curb-0.8.6/ext/gem_make.out
An error occurred while installing curb (0.8.6), and Bundler cannot continue.
Make sure that `gem install curb -v '0.8.6'` succeeds before bundling.

Installation Completed!

./creep3r

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- curb (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./creep3r:36:in `<main>'

help plzzz

**Comment by okeycik** [comment]
help plzzzzzz

**Comment by Hood3dRob1n** [comment]
make sure you have installed the ruby-dev files: 
apt-get install ruby-dev

Please let me know if this resolves your problem or not. Also which version of Kali are you installing on?

**Comment by vincentubuntu** [comment]
libcurl4-openssl-dev tell me why  have to install this? cos it always try to remove wpscan

**Comment by vincentubuntu** [comment]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/local/bin/ruby extconf.rb 
```

checking for iconv_open() in iconv.h... yes

## checking for sybfront.h... no

## freetds is missing.

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby
    --enable-lookup
    --disable-lookup
    --with-iconv-dir
    --without-iconv-dir
    --with-iconv-include
    --without-iconv-include=${iconv-dir}/include
    --with-iconv-lib
    --without-iconv-lib=${iconv-dir}/lib
    --with-freetds-dir
    --without-freetds-dir
    --with-freetds-include
    --without-freetds-include=${freetds-dir}/include
    --with-freetds-lib
    --without-freetds-lib=${freetds-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.1.0/gems/tiny_tds-0.6.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.1.0/extensions/x86-linux/2.1.0-static/tiny_tds-0.6.2/gem_make.out
An error occurred while installing tiny_tds (0.6.2), and Bundler cannot continue.
Make sure that `gem install tiny_tds -v '0.6.2'` succeeds before bundling.

Installation Completed!

**Comment by vincentubuntu** [comment]
solution for ubuntu installer
tiny_tds if this thing missing when you try to run then do 
gem install tiny_tds
and about wpscan problem just change the code in ubuntu installer replace libcurl4-openssl-dev line with libcurl4-gnutls-dev 
echo "Running Ubuntu Installer....." | grep --color 'Running Ubuntu Installer'
echo "Installing OS packages...." | grep --color 'Installing OS packages'
apt-get -y install curl libcurl3 libcurl4-gnutls-dev mysql-client libmysqlclient18 libmysqlclient-dev bundler ruby-dev nmap freetds-common freetds-bin freetds-dev libpq-dev
solve in backbox and thank you so much...

**Comment by vincentubuntu** [comment]
why the payload option is not working?

**Comment by meninbox** [comment]
Gem::InstallError: net-ssh requires Ruby version >= 2.0.
An error occured while installing net-ssh (3.1.1), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '3.1.1'` succeeds before bundling.

Please help me
